//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_movie()
        {
            this.Staff_ = new HashSet<Staff_>();
        }
    
        public int movieId { get; set; }
        public string movieName { get; set; }
        public string movieContent { get; set; }
        public System.DateTime premiereDate { get; set; }
        public string moviePhotoLink { get; set; }
        public string banerLink { get; set; }
        public string trailerLink { get; set; }
        public double review { get; set; }
        public int categoryid { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_> Staff_ { get; set; }
    }
}
