//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_
    {
        public int staffid { get; set; }
        public string staffName { get; set; }
        public System.DateTime birthday { get; set; }
        public string country { get; set; }
        public string gender { get; set; }
        public string staffPhotoLink { get; set; }
        public int movieid { get; set; }
    
        public virtual C_movie C_movie { get; set; }
    }
}
